from Ruoff.Legacy.frost import legacy_frost_notification_wrapper, about_legacy_frost, set_legacy_frost, remove_legacy_frost
from Ruoff.Legacy.olympiad import legacy_olympiad_notification_wrapper, about_legacy_olympiad, set_legacy_olympiad, remove_legacy_olympiad
